### your site title here
title: Piyush Jha
description: Ph.D. Student at Georgia Institute of Technology

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: <firstname>.<lastname>@gatech.edu

highlighter: rouge
markdown: kramdown

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
# facebook: "#"
# twitter: "#"
linkedin: "piyush-j"
github: "piyush-J"
# researchgate: "#"
orcid: "0000-0001-6513-354X"
# google_analytics: "G-F330GHLJTG"
# scopus: "#"
google_scholar: "azsq_WEAAAAJ&hl=en"
# flickr: "#"


# highlighter: rouge
# markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
# collections:
#   projects:
#     output: true
#     permalink: :path/projects/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _bibliography

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
